trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'davidgt85/python-docker'
  - name: APP_SETTINGS
    value: config.DevelopmentConfig

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'

- script: |
    pip install flask
    pip install flask_sqlalchemy
    echo $(APP_SETTINGS)
  displayName: 'Install dependencies'

- script: python devops_test/aplication.py &

steps:
 - task: Docker@2
   displayName: Build an image
   inputs:
     repository: $(imageName)
     command: build
     Dockerfile: devops_test/Dockerfile







