trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'

- script: |
    pip install flask
    pip install flask_sqlalchemy
    set APP_SETTINGS="config.DevelopmentConfig"
  displayName: 'Install dependencies'

- script: python devops_test/aplication.py