trigger:
- main
- infra

pool:
  vmImage: ubuntu-latest

variables:
  isInfra: $[eq(variables['Build.SourceBranch'], 'refs/heads/infra')]

stages:
- stage: infra
  condition: and(succeeded(), eq(variables.isInfra, 'true'))
  jobs:
  - job: A1
    steps:
      - task: CloudFormationCreateOrUpdateStack@1
        inputs:
          awsCredentials: 'Registry-test'
          regionName: 'us-east-1'
          stackName: 'PythonApp'
          templateSource: 'file'
          templateFile: 'infra/resources.yml'

- stage: app
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  jobs:
  - job: B1
    steps:
      - task: DockerInstaller@0
        inputs:
          dockerVersion: '17.09.0-ce'
      - task: Docker@2
        inputs:
          repository: 'devops-test-lahaus/lahaus_Api'
          command: 'build'
          Dockerfile: '**/Dockerfile'
          tags: |
            $(Build.BuildId)
            latest
        displayName: "Building image"
      - task: ECRPushImage@1
        inputs:
          awsCredentials: 'Registry-test'
          regionName: 'us-east-1'
          imageSource: 'imagename'
          sourceImageName: 'devops-test-lahaus/lahaus_Api'
          repositoryName: 'devops-test-lahaus'
        displayName: "Pushing image to ECR"
